In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

import torch
import torch.nn as nn
from torch.optim import Adam

from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score

from preprocessing.preprocessing import ecb_pipeline_en, fast_detect

import time

import gc

from tqdm import tqdm


torch.set_default_dtype(torch.float32)

In [2]:
FILENAME = "data/train_series.csv"
FILENAME_ECB = "data/ecb_data.csv"
FILENAME_FED = "data/fed_data.csv"

In [3]:
returns = pd.read_csv(FILENAME, index_col=0)
ecb = pd.read_csv(FILENAME_ECB, index_col=0)
fed = pd.read_csv(FILENAME_FED, index_col=0)

In [4]:
returns = pd.get_dummies(returns, columns=["Index Name"])

In [5]:
returns["Sign"] = (returns["Index + 1"] > 0).astype(int)

In [6]:
returns.head()

Index - 9  Index - 8  Index - 7  Index - 6  Index - 5  Index - 4  \
0   0.001045   0.005841   0.003832  -0.027519  -0.103565  -0.045086   
1  -0.021497   0.007891  -0.013175  -0.008436   0.000000   0.026303   
2  -0.001872  -0.008154   0.023588   0.004086   0.003493   0.003300   
3   0.004980  -0.000864   0.001677   0.000000   0.006030  -0.001083   
4   0.000360  -0.001893   0.005579  -0.003056  -0.001171  -0.001623   

   Index - 3  Index - 2  Index - 1  Index - 0  ... Index Name_CVIX Index  \
0  -0.011265   0.005164   0.054050   0.015779  ...                     0   
1   0.000556   0.001455   0.007422   0.000000  ...                     0   
2   0.000885  -0.011304   0.005040   0.000156  ...                     0   
3   0.000419   0.001492   0.001018  -0.002582  ...                     0   
4  -0.002350  -0.006444  -0.000729  -0.000365  ...                     0   

  Index Name_EURUSD Curncy  Index Name_EURUSDV1M Curncy  \
0                        0                            0   
1                        0                            0   
2                        0                            0   
3                        0                            0   
4                        1                            0   

   Index Name_MOVE Index  Index Name_SPX Index  Index Name_SRVIX Index  \
0                      0                     0                       0   
1                      1                     0                       0   
2                      0                     1                       0   
3                      0                     1                       0   
4                      0                     0                       0   

   Index Name_SX5E Index  Index Name_V2X Index  Index Name_VIX Index  Sign  
0                      0                     1                     0     1  
1                      0                     0                     0     1  
2                      0                     0                     0     1  
3                      0                     0                     0     1  
4                      0                     0                     0     1  

[5 rows x 23 columns]

In [7]:
y = returns["Sign"]

In [8]:
y.value_counts()

0    4930
1    4016
Name: Sign, dtype: int64

In [9]:
returns = returns.drop(["Sign", "Index + 1"], axis=1)

In [10]:
returns.columns

Index(['Index - 9', 'Index - 8', 'Index - 7', 'Index - 6', 'Index - 5',
       'Index - 4', 'Index - 3', 'Index - 2', 'Index - 1', 'Index - 0',
       'index ecb', 'index fed', 'Index Name_CVIX Index',
       'Index Name_EURUSD Curncy', 'Index Name_EURUSDV1M Curncy',
       'Index Name_MOVE Index', 'Index Name_SPX Index',
       'Index Name_SRVIX Index', 'Index Name_SX5E Index',
       'Index Name_V2X Index', 'Index Name_VIX Index'],
      dtype='object')

In [11]:
nontextual_cols = ['Index - 9',
 'Index - 8',
 'Index - 7',
 'Index - 6',
 'Index - 5',
 'Index - 4',
 'Index - 3',
 'Index - 2',
 'Index - 1',
 'Index - 0',
 'Index Name_CVIX Index',
 'Index Name_EURUSD Curncy',
 'Index Name_EURUSDV1M Curncy',
 'Index Name_MOVE Index',
 'Index Name_SPX Index',
 'Index Name_SRVIX Index',
 'Index Name_SX5E Index',
 'Index Name_V2X Index',
 'Index Name_VIX Index']
nb_nontextfeatures = len(nontextual_cols)

In [12]:
# 60% train, 20% val, 20% test

returns_, returns_test, y_, y_test = train_test_split(
    returns, y, test_size=0.2, train_size=0.8,
    random_state=0, stratify=y
    )

returns_train, returns_val, y_train, y_val = train_test_split(
    returns_, y_, test_size=0.25, train_size=0.75,
    random_state=42, stratify=y_
    )

In [13]:
del returns, y
gc.collect()

0

# The textual data

In [14]:
ecb.head()

title           speaker  \
0  Comments by Yves Mersch at Financial Services ...       Yves Mersch   
1  Securing sustained economic growth in the euro...  Vítor Constâncio   
2  The role of monetary policy in addressing the ...      Mario Draghi   
3  The pandemic emergency: the three challenges f...    Philip R. Lane   
4  Transmission channels of monetary policy in th...       Peter Praet   

                                                text  
0    Comments by Yves Mersch at Financial Service...  
1    Securing sustained economic growth in the eu...  
2    The role of monetary policy in addressing th...  
3     SPEECH  The pandemic emergency: the three c...  
4    Transmission channels of monetary policy in ...

In [15]:
fed.head()

title  \
0  The Importance of Economic Education and Finan...   
1       Financial Innovation and Consumer Protection   
2         Implementing Basel II in the United States   
3                  An Assessment of the U.S. Economy   
4      Monetary Policy since the Onset of the Crisis   

                                        speaker  \
0                  Governor Frederic S. Mishkin   
1                      Chairman Ben S. Bernanke   
2                  Governor Randall S. Kroszner   
3  Vice Chair for Supervision Randal K. Quarles   
4                      Chairman Ben S. Bernanke   

                                                text  
0                                             As ...  
1   The concept of financial innovation, it seems...  
2   Good afternoon. I would like to thank Standar...  
3   Thank you for the opportunity to take part in...  
4   When we convened in Jackson Hole in August 20...

In [16]:
ecb["text_"] = ecb.apply(ecb_pipeline_en, axis=1)

In [17]:
ecb["text"].fillna("", inplace=True)
ecb["speaker"].fillna("Unknown", inplace=True)
fed["speaker"].fillna("Unknown", inplace=True)

In [18]:
# Text in french
ecb.loc[138]
# Text in german
ecb.loc[151]

title                         Auf neuen Wegen zum alten Ziel
speaker                                          Yves Mersch
text         Auf neuen Wegen zum alten Ziel   Rede von Yv...
text_      Rede von Yves Mersch, Mitglied des Direktorium...
Name: 151, dtype: object

In [19]:
ecb["lang"] = ecb["text_"].apply(fast_detect)

In [20]:
ecb.head()

title           speaker  \
0  Comments by Yves Mersch at Financial Services ...       Yves Mersch   
1  Securing sustained economic growth in the euro...  Vítor Constâncio   
2  The role of monetary policy in addressing the ...      Mario Draghi   
3  The pandemic emergency: the three challenges f...    Philip R. Lane   
4  Transmission channels of monetary policy in th...       Peter Praet   

                                                text  \
0    Comments by Yves Mersch at Financial Service...   
1    Securing sustained economic growth in the eu...   
2    The role of monetary policy in addressing th...   
3     SPEECH  The pandemic emergency: the three c...   
4    Transmission channels of monetary policy in ...   

                                               text_ lang  
0  Sustainable economic growth in the real econom...   en  
1  Ladies and Gentlemen, Thank you for inviting m...   en  
2  There was a time, not too long ago, when centr...   en  
3  Today, I will discuss the monetary policy meas...   en  
4  Ladies and Gentlemen, Since the onset of the f...   en

In [21]:
fed["lang"] = fed["text"].apply(fast_detect)

In [22]:
fed.head()

title  \
0  The Importance of Economic Education and Finan...   
1       Financial Innovation and Consumer Protection   
2         Implementing Basel II in the United States   
3                  An Assessment of the U.S. Economy   
4      Monetary Policy since the Onset of the Crisis   

                                        speaker  \
0                  Governor Frederic S. Mishkin   
1                      Chairman Ben S. Bernanke   
2                  Governor Randall S. Kroszner   
3  Vice Chair for Supervision Randal K. Quarles   
4                      Chairman Ben S. Bernanke   

                                                text lang  
0                                             As ...   en  
1   The concept of financial innovation, it seems...   en  
2   Good afternoon. I would like to thank Standar...   en  
3   Thank you for the opportunity to take part in...   en  
4   When we convened in Jackson Hole in August 20...   en

In [23]:
all_langs = ecb["lang"].unique()

In [24]:
ecb["lang"].value_counts()

en    1646
de      75
fr      31
es      16
it       4
Name: lang, dtype: int64

# Translation

# HuggingFace Transformers

We test hierarchical BERT here.

In [25]:
from huggingface_hub import login

In [26]:
login(token='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')

Token will not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid.
Your token has been saved to C:\Users\huuta\.cache\huggingface\token
Login successful


In [67]:
from transformers import AutoTokenizer, AutoModel, AutoConfig

In [62]:
tokenizer = AutoTokenizer.from_pretrained("kiddothe2b/hierarchical-transformer-base-4096", trust_remote_code=True)

Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.


In [68]:
config = AutoConfig.from_pretrained("kiddothe2b/hierarchical-transformer-base-4096", trust_remote_code=True)


Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.


In [74]:
config

HATConfig {
  "_name_or_path": "kiddothe2b/hierarchical-transformer-base-4096",
  "architectures": [
    "HATForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "auto_map": {
    "AutoConfig": "configuration_hat.HATConfig",
    "AutoModel": "modelling_hat.HATModel",
    "AutoModelForMaskedLM": "modelling_hat.HATForMaskedLM",
    "AutoModelForMultipleChoice": "modelling_hat.HATForMultipleChoice",
    "AutoModelForQuestionAnswering": "modelling_hat.HATForQuestionAnswering",
    "AutoModelForSequenceClassification": "modelling_hat.HATForSequenceClassification",
    "AutoModelForTokenClassification": "modelling_hat.HATForTokenClassification",
    "AutoTokenizer": "tokenization_hat.HATTokenizer"
  },
  "bos_token_id": 0,
  "classifier_dropout": null,
  "encoder_layout": {
    "0": {
      "document_encoder": false,
      "sentence_encoder": true
    },
    "1": {
      "document_encoder": false,
      "sentence_encoder": true
    },
    "10": {
      "document_encoder": false,
      

In [63]:
model = AutoModel.from_pretrained("kiddothe2b/hierarchical-transformer-base-4096", trust_remote_code=True)


Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Some weights of the model checkpoint at kiddothe2b/hierarchical-transformer-base-4096 were not used when initializing HATModel: ['hi_transformer.encoder.layer.1.sentence_encoder.attention.output.dense.bias', 'hi_transformer.encoder.layer.7.sentence_encoder.attention.output.LayerNorm.weight', 'hi_transformer.encoder.layer.0.sentence_encoder.output.LayerNorm.weight', 'hi_transformer.encoder.layer.10.sentence_encoder.output.dense.weight', 'hi_transformer.encoder.layer.8.document_encoder.attention.self.value.weight', 'hi_transformer.encoder.layer.10.sentence_encoder.attention.output.LayerNorm.bias', 'hi_transformer.encoder.layer.1.sentence_encoder.intermediate.dense.weight', 'hi_

In [64]:
tokenizer?

Signature:   tokenizer(text, **kwargs)
Type:        HATTokenizer
String form: <transformers_modules.kiddothe2b.hierarchical-transformer-base-4096.97ba9b93529bf90c29e36389eb079caa2b203dd8.tokenization_hat.HATTokenizer object at 0x00000202FC8D8FD0>
Length:      50265
File:        c:\users\huuta\.cache\huggingface\modules\transformers_modules\kiddothe2b\hierarchical-transformer-base-4096\97ba9b93529bf90c29e36389eb079caa2b203dd8\tokenization_hat.py
Docstring:   <no docstring>

In [65]:
# One must provide a list of strings to the tokenizer. A single string won't work.
tokens = tokenizer(["Hello world"], padding='max_length', max_length=4096)
print(tokens["input_ids"])
print(tokens["attention_mask"])

[[0, 31414, 232, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [66]:
output = model(torch.Tensor(tokens["input_ids"]).int(), attention_mask = torch.Tensor(tokens["attention_mask"]).int())
print(output)

c:\Users\huuta\anaconda3\envs\nlp-env\lib\site-packages\transformers\modeling_utils.py:713: FutureWarning: The `device` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(


BaseModelOutputWithSentenceAttentions(last_hidden_state=tensor([[[ 0.2913, -1.4626, -0.0767,  ...,  1.8455,  0.2612,  1.3971],
         [ 1.2999, -1.1006, -0.3852,  ...,  1.4813,  0.9634,  0.9905],
         [-0.0073, -1.4696, -0.8785,  ...,  1.0659,  0.5045,  1.4827],
         ...,
         [ 1.2753, -1.0961, -1.6010,  ...,  1.0138, -0.2057,  1.3753],
         [ 1.2753, -1.0961, -1.6010,  ...,  1.0138, -0.2057,  1.3753],
         [ 1.2753, -1.0961, -1.6010,  ...,  1.0138, -0.2057,  1.3753]]],
       grad_fn=<AsStridedBackward0>), hidden_states=None, attentions=None, sentence_attentions=None)


In [56]:
model?

Signature:      model(*input, **kwargs)
Type:           HATForMaskedLM
String form:   
HATForMaskedLM(
           (hi_transformer): HATModel(
           (embeddings): HATEmbeddings(
           (word_embedd <...> mentwise_affine=True)
           (decoder): Linear(in_features=768, out_features=50265, bias=True)
           )
           )
File:           c:\users\huuta\.cache\huggingface\modules\transformers_modules\kiddothe2b\hierarchical-transformer-base-4096\97ba9b93529bf90c29e36389eb079caa2b203dd8\modelling_hat.py
Docstring:     
HAT Model with a `language modeling` head on top.

This model inherits from [`PreTrainedModel`]. Check the superclass documentation for the generic methods the
library implements for all its model (such as downloading or saving, resizing the input embeddings, pruning heads
etc.)

This model is also a PyTorch [torch.nn.Module](https://pytorch.org/docs/stable/nn.html#torch.nn.Module) subclass.
Use it as a regular PyTorch Module and refer to the PyTorch documenta

In [ ]:
class AttentivePooling(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.attn_dropout = config.hidden_dropout_prob
        self.lin_proj = nn.Linear(config.hidden_size, config.hidden_size)
        self.v = nn.Linear(config.hidden_size, 1, bias=False)

    def forward(self, inputs):
        lin_out = self.lin_proj(inputs)
        attention_weights = torch.tanh(self.v(lin_out)).squeeze(-1)
        attention_weights_normalized = torch.softmax(attention_weights, -1)
        return torch.sum(attention_weights_normalized.unsqueeze(-1) * inputs, 1)


class HATPooler(nn.Module):
    def __init__(self, config, pooling='max'):
        super().__init__()
        self.dense = nn.Linear(config.hidden_size, config.hidden_size)
        self.pooling = pooling
        if self.pooling == 'attentive':
            self.attentive_pooling = AttentivePooling(config)
        self.activation = nn.Tanh()
        self.max_sentence_length = config.max_sentence_length

    def forward(self, hidden_states):
        if self.pooling == 'attentive':
            pooled_output = self.attentive_pooling(hidden_states)
        else:
            pooled_output = torch.max(hidden_states, dim=1)[0]
        pooled_output = self.dense(pooled_output)
        pooled_output = self.activation(pooled_output)
        return pooled_output

# Loading data

In [31]:
from model.framework_dataset import get_data_loader
from model.framework_model import CorpusEncoder, ClassificationHead, MyModel

In [32]:
config = {

    "method": "model_01",

    "learning_rate": 0.001,

    "weight_decay": 0.,

    "batch_size": 2,

    "layers": 3,

    "dropout": 0.3,

    "separate": True,
    
    "max_corpus_len": 2

}

In [33]:
train_set, train_loader, tokenizer, steps = get_data_loader(
    returns_train, ecb, fed, y_train, method=config["method"],
    separate=config["separate"], max_corpus_len=config["max_corpus_len"],
    batch_size=config["batch_size"]
)

val_set, val_loader, tokenizer, steps = get_data_loader(
    returns_val, ecb, fed, y_val, method=config["method"],
    separate=config["separate"], max_corpus_len=config["max_corpus_len"],
    batch_size=config["batch_size"]
)

test_set, test_loader, tokenizer, steps = get_data_loader(
    returns_test, ecb, fed, y_test, method=config["method"],
    separate=config["separate"], max_corpus_len=config["max_corpus_len"],
    batch_size=config["batch_size"]
)

# Loading model

In [34]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
#device = torch.device("cpu")

In [35]:
ce = CorpusEncoder(method=config["method"],
                   separate=config["separate"],
                   dropout=config["dropout"]).to(device)
clf = ClassificationHead(
    corpus_emb_dim=ce.corpus_emb_dim, nontext_dim=nb_nontextfeatures,
    layers=config["max_corpus_len"], dropout=config["dropout"]
).to(device)
my_model = MyModel(
    nontext_dim=nb_nontextfeatures, method=config["method"],
    separate=config["separate"], dropout=config["dropout"]
).to(device)

Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertModel: ['vocab_transform.bias', 'vocab_layer_norm.weight', 'vocab_layer_norm.bias', 'vocab_projector.weight', 'vocab_projector.bias', 'vocab_transform.weight']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertModel: ['vocab_transform.bias', 'vocab_layer_norm.weight', 'vocab_layer_norm.bias', 'vocab_projector.weight', 'vocab_projector.bias', 'vocab_transform.weight']
- T

In [36]:
# Test output
batch = next(iter(val_loader))

with torch.no_grad():
    ce.eval()
    X_ecb = batch["X_ecb"].to(device)
    X_ecb_att = batch["X_ecb_mask"].to(device)
    X_fed = batch["X_fed"].to(device)
    X_fed_att = batch["X_fed_mask"].to(device)
    X_ind =  batch["X_ind"].to(device)
    y = batch["label"]
    X_text = (X_ecb, X_fed)
    X_att = (X_ecb_att, X_fed_att)
    ce_output = ce(X_text, X_att)
    print("Computed output successfully. ce ouput = \n", ce_output)
    print("corpus encoder ouput shape = ", ce_output.size(), "\ncorpus embed dim = ", ce.corpus_emb_dim)
    print(X_ind.size())


    clf_output = clf(ce_output, X_ind)
    
    print("Classifier output =  \n", clf_output)
    my_model_output = my_model(X_text, X_att, X_ind)

print(X_ecb.size())
print(X_ecb_att.size())
print(y)

Computed output successfully. ce ouput = 
 tensor([[ 0.5188,  0.3291,  0.1633, -0.1473,  0.1349, -0.4494, -0.3119,  0.1545,
          0.0786, -0.2876,  0.3910,  0.3875, -0.3660, -0.3608,  0.2498, -0.2504,
         -0.2098,  0.4205,  0.4584, -0.0644,  0.0358,  0.1918, -0.0308,  0.3077,
          0.1890, -0.0861,  0.0858, -0.8284, -0.1828,  0.4115,  0.1117,  0.2787,
         -0.2774,  0.3394,  0.0273,  0.5999,  0.1513,  0.1244,  0.1631, -0.2311,
         -0.3805,  0.0701,  0.0895,  0.0474,  0.1385, -0.0742, -0.2884,  0.4224,
         -0.0044, -0.3157, -0.0460, -0.1186, -0.3529, -0.1792,  0.4930,  0.2769,
          0.0461, -0.0694, -0.0678, -0.1934,  0.0267,  0.0373,  0.0128, -0.3020],
        [ 0.4916,  0.3016,  0.1952,  0.0704,  0.1516, -0.3817, -0.3201,  0.0201,
          0.0241, -0.2107,  0.4107,  0.4672, -0.2213, -0.2495,  0.1668, -0.1596,
         -0.0287,  0.3923,  0.3666, -0.0917,  0.0404,  0.1947, -0.0886,  0.3141,
          0.0573, -0.0093,  0.1364, -0.6961, -0.1473,  0.2655,  0

# Other example

In [37]:
config = {

    "method": "model_01",

    "learning_rate": 0.001,

    "weight_decay": 0.,

    "batch_size": 2,

    "layers": 3,

    "dropout": 0.5,

    "separate": False,
    
    "max_corpus_len": 2


}

In [38]:
train_set, train_loader, tokenizer, steps = get_data_loader(
    returns_train, ecb, fed, y_train, method=config["method"],
    separate=config["separate"], max_corpus_len=config["max_corpus_len"],
    batch_size=config["batch_size"]
)

val_set, val_loader, tokenizer, steps = get_data_loader(
    returns_val, ecb, fed, y_val, method=config["method"],
    separate=config["separate"], max_corpus_len=config["max_corpus_len"],
    batch_size=config["batch_size"]
)

test_set, test_loader, tokenizer, steps = get_data_loader(
    returns_test, ecb, fed, y_test, method=config["method"],
    separate=config["separate"], max_corpus_len=config["max_corpus_len"],
    batch_size=config["batch_size"]
)

In [39]:
ce = CorpusEncoder(method=config["method"],
                   separate=config["separate"],
                   dropout=config["dropout"]).to(device)
clf = ClassificationHead(
    corpus_emb_dim=ce.corpus_emb_dim, nontext_dim=nb_nontextfeatures,
    layers=config["max_corpus_len"], dropout=config["dropout"]
).to(device)
my_model = MyModel(
    nontext_dim=nb_nontextfeatures, method=config["method"],
    separate=config["separate"], dropout=config["dropout"]
).to(device)

Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertModel: ['vocab_transform.bias', 'vocab_layer_norm.weight', 'vocab_layer_norm.bias', 'vocab_projector.weight', 'vocab_projector.bias', 'vocab_transform.weight']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertModel: ['vocab_transform.bias', 'vocab_layer_norm.weight', 'vocab_layer_norm.bias', 'vocab_projector.weight', 'vocab_projector.bias', 'vocab_transform.weight']
- T

In [40]:
z = torch.range(0, 15)
print(z)
z.view(4, 4)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15.])


C:\Users\ready\AppData\Local\Temp\ipykernel_4736\1290859485.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  z = torch.range(0, 15)


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

In [41]:
# Test output
batch = next(iter(val_loader))

with torch.no_grad():
    ce.eval()
    X_text = (batch["X_text"].to(device),)
    X_mask = (batch["X_mask"].to(device),)
    X_ind =  batch["X_ind"].to(device)
    y = batch["label"]
    ce_output = ce(X_text, X_mask)
    print("Computed output successfully. ce ouput = \n", ce_output)
    print("corpus encoder ouput shape = ", ce_output.size(), "\ncorpus embed dim = ", ce.corpus_emb_dim)
    print(X_ind.size())


    clf_output = clf(ce_output, X_ind)
    
    print("Classifier output =  \n", clf_output)
    my_model_output = my_model(X_text, X_mask, X_ind)

print(X_ecb)
print(X_ecb_att)
print(y)

Computed output successfully. ce ouput = 
 tensor([[ 0.4157,  0.1194,  0.3883,  0.0341,  0.0856,  0.1622,  0.0121,  0.0527,
         -0.2364, -0.3298,  0.0536, -0.1610, -0.0075, -0.1486, -0.4683, -0.4899,
         -0.3891,  0.0252,  0.0037, -0.3633, -0.2859, -0.0357,  0.0311,  0.3272,
          0.0782,  0.2936, -0.2265,  0.0849,  0.4000, -0.1206, -0.0824,  0.0014],
        [ 0.4882,  0.1265,  0.3807,  0.0256,  0.0367,  0.0750, -0.0288,  0.0552,
         -0.3381, -0.3272, -0.0165, -0.1988,  0.0848, -0.1289, -0.4908, -0.5434,
         -0.3220,  0.0030, -0.0315, -0.3173, -0.3220,  0.0066,  0.0303,  0.3315,
          0.1331,  0.2751, -0.2566,  0.1179,  0.3966, -0.0763, -0.0906,  0.0263]],
       dtype=torch.float64)
corpus encoder ouput shape =  torch.Size([2, 32]) 
corpus embed dim =  32
torch.Size([2, 19])
Classifier output =  
 tensor([0.5048, 0.5103])
tensor([[[  101, 21658,  3242,  ...,  2008, 17653,   102],
         [  101,   102,     0,  ...,     0,     0,     0]],

        [[  101,

# Testing train code

In [42]:
from train import train, evaluate

In [43]:
train(my_model, train_loader=train_loader, val_loader=val_loader,config=config,
      device=device, max_epochs=1, eval_every=1, name="dummy")

Epoch 0:   0%|          | 10/2684 [01:43<7:40:26, 10.33s/batch, accuracy=55, loss=0.687] 


KeyboardInterrupt: 